"use client";

import { useState } from "react";
import { useToast } from "@/components/ToastContext";
import { Eye, FileText, Send, MoreHorizontal } from "lucide-react";

interface Invoice {
  id: string;
  awb: string;
  consignee: string;
  amount: number;
  status: string;
  generatedAt: string;
  generatedBy: string;
}

interface RecentInvoicesProps {
  invoices: Invoice[];
}

const statusConfig: Record<string, { bg: string; text: string; dot: string }> = {
  Sent: { bg: "#DBEAFE", text: "#1B4F8B", dot: "#2E75B6" },
  Paid: { bg: "#DCFCE7", text: "#16A34A", dot: "#16A34A" },
  Overdue: { bg: "#FEE2E2", text: "#DC2626", dot: "#DC2626" },
  Draft: { bg: "#F1F5F9", text: "#64748B", dot: "#94A3B8" },
};

function formatPKR(value: number) {
  return `Rs. ${value.toLocaleString("en-PK")}`;
}

export default function RecentInvoices({ invoices }: RecentInvoicesProps) {
  const { addToast } = useToast();
  const [actionOpenRow, setActionOpenRow] = useState<number | null>(null);

  const handleAction = (action: string, id: string) => {
    addToast(`${action} for ${id}`, "success");
  };

  return (
    <div className="rounded-[16px] border border-[#E2E8F0] bg-white shadow-sm overflow-hidden">
      <div className="flex items-center justify-between px-5 py-4 border-b border-[#E2E8F0]">
        <div className="flex items-center gap-2.5">
          <h2 className="text-[15px] font-bold text-[#0F172A]">Recent Invoices</h2>
          <span className="text-[12px] text-[#64748B] ml-1">{invoices.length} invoices</span>
        </div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full min-w-[900px]">
          <thead>
            <tr className="border-b border-[#E2E8F0] bg-[#F8FAFC]">
              {["Invoice #", "AWB #", "Consignee", "Amount PKR", "Status", "Generated At", "Generated By", "Action"].map(
                (h) => (
                  <th
                    key={h}
                    className="text-left text-[11px] font-semibold text-[#64748B] uppercase tracking-wider px-4 py-3 whitespace-nowrap"
                  >
                    {h}
                  </th>
                )
              )}
            </tr>
          </thead>
          <tbody>
            {invoices.map((inv, idx) => {
              const sc = statusConfig[inv.status] || statusConfig.Draft;
              return (
                <tr key={inv.id} className="border-b border-[#E2E8F0] hover:bg-[#F8FAFC] transition-colors">
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] font-semibold text-[#0B2545]">{inv.id}</span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] text-[#475569]">{inv.awb}</span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] text-[#475569]">{inv.consignee}</span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] font-semibold text-[#0F172A]">{formatPKR(inv.amount)}</span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span
                      className="inline-flex items-center gap-1.5 h-6 px-2.5 rounded-full text-[11px] font-semibold whitespace-nowrap"
                      style={{ backgroundColor: sc.bg, color: sc.text }}
                    >
                      <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: sc.dot }} />
                      {inv.status}
                    </span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] text-[#475569]">{inv.generatedAt}</span>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="text-[13px] text-[#475569]">{inv.generatedBy}</span>
                  </td>
                  <td className="px-4 py-3.5 relative">
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleAction("Viewed", inv.id)}
                        className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F1F5F9] text-[#64748B] hover:text-[#0B2545] cursor-pointer transition-colors"
                        title="View"
                      >
                        <Eye size={15} />
                      </button>
                      <button
                        onClick={() => handleAction("Downloaded", inv.id)}
                        className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F1F5F9] text-[#64748B] hover:text-[#1B4F8B] cursor-pointer transition-colors"
                        title="Download PDF"
                      >
                        <FileText size={15} />
                      </button>
                      <button
                        onClick={() => handleAction("Emailed", inv.id)}
                        className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F1F5F9] text-[#64748B] hover:text-[#16A34A] cursor-pointer transition-colors"
                        title="Email"
                      >
                        <Send size={15} />
                      </button>
                      <button
                        onClick={() => setActionOpenRow(actionOpenRow === idx ? null : idx)}
                        className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F1F5F9] text-[#64748B] hover:text-[#0B2545] cursor-pointer transition-colors"
                      >
                        <MoreHorizontal size={15} />
                      </button>
                    </div>
                    {actionOpenRow === idx && (
                      <div className="absolute right-4 top-12 z-10 w-[160px] bg-white rounded-xl shadow-lg border border-[#E2E8F0] overflow-hidden">
                        <button className="w-full text-left px-3 py-2 text-[13px] text-[#0F172A] hover:bg-[#F8FAFC] cursor-pointer flex items-center gap-2">
                          <Eye size={14} className="text-[#64748B]" /> View Detail
                        </button>
                        <button className="w-full text-left px-3 py-2 text-[13px] text-[#0F172A] hover:bg-[#F8FAFC] cursor-pointer flex items-center gap-2">
                          <FileText size={14} className="text-[#64748B]" /> Download PDF
                        </button>
                        <button className="w-full text-left px-3 py-2 text-[13px] text-[#0F172A] hover:bg-[#F8FAFC] cursor-pointer flex items-center gap-2">
                          <Send size={14} className="text-[#64748B]" /> Resend Email
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}