/**
 * Reference data transcribed from the **actual** SAPS documents.
 *
 * Unlike everything in `fixtures.ts`, none of this is invented. It is
 * flight OD 0131 / 01-Aug-2026 KUL→LHE and its three AWBs, transcribed
 * from the supplied scans. Every figure reconciles:
 *
 *   ULD BULK        4 + 9 pcs   =  344.00 kg   GWGT   344.00  tare   0
 *   ULD PAG40387JT     61 pcs   = 1200.00 kg   GWGT 1,320.00  tare 120
 *   ULD PAG40479JT     84 pcs   = 1958.00 kg   GWGT 2,078.00  tare 120
 *   TOTALS            158 pcs   = 3502.00 kg
 *
 * AWB 816-00052345 arrives split across two ULDs — 61/145 and 84/145 —
 * which is the case CMTS cannot express and FC-01 §07 does not describe.
 *
 * Used as the worked example on the manifest and OCR screens so the demo
 * can be checked against paper rather than taken on trust.
 */

import type { AwbDocument, ManifestLine, UldRecord } from "./awbdoc";

export const REFERENCE_FLIGHT = {
  operator: "Batik Air",
  registration: "9MLFC",
  flightNo: "OD 0131",
  flightDate: "2026-08-01",
  pointOfLoading: "KUL",
  pointOfUnloading: "LHE",
  preparedBy: "MAZUANH",
  formReference: "I.C.A.O ANNEX 9",
  totals: { pieces: 158, netWeightKg: 3502.0 },
} as const;

export const REFERENCE_ULDS: UldRecord[] = [
  {
    uldId: "BULK",
    isBulk: true,
    grossWeightKg: 344.0,
    netWeightKg: 344.0,
    tareWeightKg: 0,
    disposition: "LOCAL",
    contour: null,
  },
  {
    uldId: "PAG40387JT",
    isBulk: false,
    grossWeightKg: 1320.0,
    netWeightKg: 1200.0,
    tareWeightKg: 120.0,
    disposition: "LOCAL",
    contour: null,
  },
  {
    uldId: "PAG40479JT",
    isBulk: false,
    grossWeightKg: 2078.0,
    netWeightKg: 1958.0,
    tareWeightKg: 120.0,
    disposition: "LOCAL",
    contour: null,
  },
];

export const REFERENCE_MANIFEST_LINES: ManifestLine[] = [
  {
    id: 1,
    ManifiestId: 0,
    uldId: "BULK",
    AWBNO: "816-00059205",
    piecesOnUld: 4,
    piecesOnAwb: null,
    netWeightKg: 112.0,
    origin: "DEL",
    destination: "LHE",
    description: "PHARMA",
    scc: "GEN",
    nextFlight: null,
    customsStatus: null,
    remarks: null,
  },
  {
    id: 2,
    ManifiestId: 0,
    uldId: "BULK",
    AWBNO: "816-00034156",
    piecesOnUld: 9,
    piecesOnAwb: null,
    netWeightKg: 232.0,
    origin: "DEL",
    destination: "LHE",
    description: "PHARMA",
    scc: "GEN",
    nextFlight: null,
    customsStatus: null,
    remarks: null,
  },
  {
    id: 3,
    ManifiestId: 0,
    uldId: "PAG40387JT",
    AWBNO: "816-00052345",
    // The manifest prints "61/145" — this AWB is split across two ULDs.
    piecesOnUld: 61,
    piecesOnAwb: 145,
    netWeightKg: 1200.0,
    origin: "DAD",
    destination: "LHE",
    description: "KNITED FABRIC",
    scc: "GEN",
    nextFlight: null,
    customsStatus: null,
    remarks: null,
  },
  {
    id: 4,
    ManifiestId: 0,
    uldId: "PAG40479JT",
    AWBNO: "816-00052345",
    piecesOnUld: 84,
    piecesOnAwb: 145,
    netWeightKg: 1958.0,
    origin: "DAD",
    destination: "LHE",
    description: "KNITED FABRIC",
    scc: "GEN",
    nextFlight: null,
    customsStatus: null,
    remarks: null,
  },
];

export const REFERENCE_AWB_DOCUMENTS: AwbDocument[] = [
  {
    AWBNO: "816-00059205",
    airlinePrefix: "816",
    originCode: "DEL",
    serialNo: "00059205",
    airportOfDeparture: "DELHI",
    routing: [
      { leg: 1, to: "KUL", byCarrier: "BATIK AIR MALAYSIA", flightNo: "OD0206", flightDate: "2026-07-31" },
      { leg: 2, to: "LHE", byCarrier: "OD", flightNo: "OD0131", flightDate: "2026-08-02" },
    ],
    issuingAgentName: "FEI CARGO LTD.",
    issuingAgentCity: "NEW DELHI",
    agentIataCode: "14-3-5164",
    shipperAccountNo: null,
    consigneeAccountNo: null,
    notifyParty1: "MEDPHARM RESEARCH LAB, 28 KM FEROZPUR ROAD, LAHORE",
    notifyParty2: null,
    currency: "INR",
    chargeCode: "PP",
    wtValPrepaid: true,
    otherPrepaid: true,
    declaredValueCarriage: "NVC",
    declaredValueCustoms: "NVD",
    amountOfInsurance: "XXX",
    rateClass: "Q",
    commodityItemNo: null,
    weightUnit: "K",
    grossWeightKg: 112.0,
    netWeightKg: null,
    chargeableWeightKg: 112.0,
    rate: 330.0,
    weightCharge: 36960.0,
    dimensionUnit: "cm",
    dimensionsText: "44x40x40 (4)",
    totalVolume: 281600,
    volumeUnit: "ccm",
    otherCharges: [
      { code: "AMS", description: "Automated manifest system", amount: 250.0, dueTo: "carrier" },
      { code: "AWB", description: "Air waybill fee", amount: 400.0, dueTo: "agent" },
      { code: "AWF", description: "Airway bill fee (carrier)", amount: 150.0, dueTo: "carrier" },
      { code: "FSCC", description: "Fuel surcharge (carrier)", amount: 30520.0, dueTo: "carrier" },
    ],
    totalOtherChargesDueAgent: 400.0,
    totalOtherChargesDueCarrier: 31760.0,
    totalPrepaid: 69120.0,
    totalCollect: 0,
    exporterHsCode: "29339990",
    importerHsCode: "29362900",
    commercialInvoiceNo: "CLL/EXP/26-27/24",
    commercialInvoiceDate: null,
    importContractNo: null,
    importContractDate: null,
    bankContractNo: "HMBC/02-07/1152",
    bankContractDate: "2026-06-30",
    handlingNtn: "89531-92-1",
    sci: null,
    pharma: null,
    handlingInformation:
      "PLS INFORM CONSIGNEE IMMDLY ON ARRIVAL AT DESTINATION // MEDPHARM RESEARCH LAB",
    executedOnDate: "2026-07-30",
    executedAtPlace: "DELHI",
    site: "LHE",
  },
  {
    AWBNO: "816-00034156",
    airlinePrefix: "816",
    originCode: "DEL",
    serialNo: "00034156",
    airportOfDeparture: "NEW DELHI, INDIA",
    routing: [
      { leg: 1, to: "KUL", byCarrier: "OD", flightNo: "OD0206", flightDate: "2026-07-31" },
      { leg: 2, to: "LHE", byCarrier: "OD", flightNo: "OD0131", flightDate: "2026-08-05" },
    ],
    issuingAgentName: "YFC AVIATION",
    issuingAgentCity: "NEW DELHI",
    agentIataCode: "14-3-2896",
    shipperAccountNo: null,
    consigneeAccountNo: null,
    notifyParty1:
      "RELIZON PHARMACEUTICALS, PLOT NO.118, SUNDAR INDUSTRIAL ESTATE, SUNDAR RAIWIND RD, LAHORE — NTN 7981230-3",
    notifyParty2: "MEEZAN BANK LTD., PAKISTAN",
    currency: "INR",
    chargeCode: "PP",
    wtValPrepaid: true,
    otherPrepaid: true,
    declaredValueCarriage: "NVD",
    declaredValueCustoms: "NCV",
    amountOfInsurance: "NIL",
    rateClass: "Q",
    commodityItemNo: "K",
    weightUnit: "K",
    grossWeightKg: 231.6,
    netWeightKg: null,
    // 231.6 rounded up to the next 0.5 kg — the IATA rule FC-07 §06 omits.
    chargeableWeightKg: 232.0,
    rate: 330.0,
    weightCharge: 76560.0,
    // Computed in INCHES — divisor 366, not 6000.
    dimensionUnit: "in",
    dimensionsText: "14X14X21 / 9",
    totalVolume: 37044,
    volumeUnit: "cuin",
    otherCharges: [
      { code: "AWB", description: "Air waybill fee", amount: 150.0, dueTo: "agent" },
      { code: "PCA", description: "Processing / clearance admin", amount: 250.0, dueTo: "agent" },
      { code: "CGST", description: "Central GST", amount: 36.0, dueTo: "agent" },
      { code: "SGST", description: "State GST", amount: 36.0, dueTo: "agent" },
      { code: "AMS", description: "Automated manifest system", amount: 250.0, dueTo: "carrier" },
      { code: "FSC", description: "Fuel surcharge", amount: 1624.0, dueTo: "carrier" },
    ],
    totalOtherChargesDueAgent: 472.0,
    totalOtherChargesDueCarrier: 1874.0,
    totalPrepaid: 78906.0,
    totalCollect: 0,
    exporterHsCode: "29224990",
    importerHsCode: null,
    commercialInvoiceNo: "VEMEDEXP-07/2627",
    commercialInvoiceDate: "2026-06-20",
    importContractNo: "26RCIS0292-01372",
    importContractDate: "2026-06-16",
    bankContractNo: null,
    bankContractDate: null,
    handlingNtn: "7981230-3",
    sci: null,
    pharma: {
      batchNo: "PGL260053FP",
      manufactureDate: "2026-05",
      retestOrExpiryDate: "2029-04",
      dateBasis: "retest",
    },
    handlingInformation: "9 PKG MRKD PLS INFRM TO CNEE ON ARVL OF GOODS AT DESTINATION",
    executedOnDate: "2026-07-30",
    executedAtPlace: "NEW DELHI",
    site: "LHE",
  },
  {
    AWBNO: "816-00052345",
    airlinePrefix: "816",
    originCode: "DAD",
    serialNo: "00052345",
    airportOfDeparture: "DA NANG",
    routing: [
      { leg: 1, to: "KUL", byCarrier: "OD", flightNo: "OD503", flightDate: "2026-07-28" },
      { leg: 2, to: "LHE", byCarrier: "OD", flightNo: "OD131", flightDate: "2026-07-31" },
    ],
    issuingAgentName: "FAR EAST AVIATION",
    issuingAgentCity: "DA NANG",
    agentIataCode: null,
    shipperAccountNo: null,
    consigneeAccountNo: null,
    notifyParty1: "SAME AS CONSIGNEE",
    notifyParty2: null,
    currency: "USD",
    chargeCode: "CC",
    wtValPrepaid: false,
    otherPrepaid: false,
    declaredValueCarriage: "NVD",
    declaredValueCustoms: "NCV",
    amountOfInsurance: "XXX",
    rateClass: "Q",
    commodityItemNo: null,
    weightUnit: "K",
    grossWeightKg: 3158.0,
    // The HAWB declares NW 3,061.3 and GW 3,148.3 — 9.7 kg below the MAWB.
    netWeightKg: 3061.3,
    chargeableWeightKg: 3158.0,
    rate: 5.16,
    weightCharge: 16295.28,
    dimensionUnit: "cm",
    dimensionsText: "165x20x20 (CM) / 145",
    totalVolume: 16,
    volumeUnit: "cbm",
    otherCharges: [
      { code: "AWC", description: "Air waybill charge", amount: 5.16, dueTo: "agent" },
      { code: "FIH", description: "Freight in handling", amount: 7.0, dueTo: "agent" },
      { code: "FWB", description: "Electronic AWB fee", amount: 5.0, dueTo: "agent" },
      { code: "SYS", description: "System / message fee", amount: 3.0, dueTo: "agent" },
      { code: "X-RAY", description: "Security screening", amount: 59.05, dueTo: "agent" },
    ],
    totalOtherChargesDueAgent: 79.21,
    totalOtherChargesDueCarrier: 0,
    totalPrepaid: 16374.49,
    totalCollect: 0,
    exporterHsCode: "60053790",
    importerHsCode: null,
    commercialInvoiceNo: "P126700356",
    commercialInvoiceDate: null,
    importContractNo: null,
    importContractDate: null,
    bankContractNo: null,
    bankContractDate: null,
    handlingNtn: "0388476-2",
    sci: null,
    pharma: null,
    handlingInformation: "HAWB 1 · DAD-KUL OD503/28JUL26 · KUL-LHE OD131/31JUL26",
    executedOnDate: "2026-07-28",
    executedAtPlace: "HO CHI MINH CITY",
    site: "LHE",
  },
];

/**
 * The HAWB under the CONSOL master, from page 2 of 816-0005-2345.
 * Its gross weight (3,148.3) is 9.7 kg below the MAWB's (3,158.00) — the
 * kind of master-vs-house divergence FC-04 should surface rather than
 * absorb silently.
 */
export const REFERENCE_HAWB = {
  hawbNo: "GCS26070055",
  masterAwbNo: "816-00052345",
  issuedBy: "GREEN CARGO SERVICES",
  shipper: "UNIVERSAL STAR CORPORATION, APIA, SAMOA",
  consignee: "STYLE TEXTILE (PVT) LTD, 126/3 KOT LAKHPAT INDUSTRIAL ESTATE, LAHORE",
  notifyParty: "SAME AS CONSIGNEE",
  pieces: 145,
  grossWeightKg: 3148.3,
  netWeightKg: 3061.3,
  chargeableWeightKg: 3158.0,
  volumeCbm: 16,
  goods: "KNITED FABRIC",
  productCode: "P126700356",
  rolls: 145,
  yards: 11668,
  dimensionsText: "165x20x20(CM) / 145",
  chargeCode: "CC" as const,
  rate: "AS ARRANGED",
} as const;

/** Master-vs-house divergence on the reference consolidation. */
export const REFERENCE_HAWB_DIVERGENCE = {
  masterGrossKg: 3158.0,
  houseGrossKg: REFERENCE_HAWB.grossWeightKg,
  deltaKg: Math.round((3158.0 - REFERENCE_HAWB.grossWeightKg) * 10) / 10,
  note: "House gross is 9.7 kg below the master. Typical of ULD tare or packing allowance, but it is a real divergence and should be an explicit reconciliation line rather than absorbed.",
} as const;
